export { default as UserInput } from "./UserInput";
export { default as ErrorPages } from "./ErrorPages";
export { default as MessageInput } from "./MessageInput";
export { default as ModalNext } from "./ModalNext";
export { default as EndPage } from "./EndPage";
export { default as FinalPage } from "./FinalPage";
export { default as MessagePeople } from "./MessagePeople";
export { default as Ending } from "./Ending";
export { default as MessageForKenny } from "./MessageForKenny";
